# Generated by Django 5.1.8 on 2025-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='num',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='additional',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='daily_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='monthly_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='operator_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
