# Generated by Django 5.1.8 on 2025-07-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_criteria_rename_num_operator_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
