# Generated by Django 5.1.8 on 2025-07-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_requestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='additional',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='additional',
            name='num_app',
        ),
        migrations.RemoveField(
            model_name='additional',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='additional',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='additional',
            name='service_id',
        ),
    ]
