# Generated by Django 5.1.8 on 2025-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_additional_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional',
            new_name='Theme',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='theme',
            new_name='title',
        ),
    ]
