# Generated by Django 5.1.8 on 2025-07-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_additional_theme_rename_theme_theme_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theme'),
        ),
    ]
