# Generated by Django 5.1.8 on 2025-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='icons',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
    ]
