# Generated by Django 5.1.8 on 2025-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_urls_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
